// <auto-generated />
using DomainSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainSearch.Data.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DomainSearch.Data.Domain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DomainSearch.Data.Offer", b =>
                {
                    b.Property<string>("DomainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registrar")
                        .HasColumnType("TEXT");

                    b.Property<float>("DollarsPerYear")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DomainId", "Registrar");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("DomainSearch.Data.Offer", b =>
                {
                    b.HasOne("DomainSearch.Data.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });
#pragma warning restore 612, 618
        }
    }
}
